repositoryUrl: https://github.com/Datatamer/tamr-cloud-sdk-python
branches: main
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/exec"
    - prepareCmd: "pip install toml-cli && toml set --toml-path pyproject.toml tool.poetry.version ${nextRelease.version}"
      publishCmd: "poetry install --no-dev && poetry publish -r artifactory --build"
  - - "@semantic-release/github"
    - assets:
      - path: "dist/tamr_cloud_sdk*"