name: CI

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
    branches:
      - main
      - release-*
  workflow_dispatch:

jobs:
  Lint_Format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    - name: Install requirements
      run: | 
        python3.11 -m pip install -r requirements_dev.txt
        python3.11 -m pip install -r requirements.txt
    - name: Run ruff checks
      run: |
        ruff check --select I
        ruff format --check
